title: kim min seong
description: > # this means to ignore newlines until "baseurl:"
  새 시즌 그마 도전

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rlaalastjd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: kim min seong
tagline: 롤체 챌린저
about-description: 새 시즌 그마 도전
# Add Discription
pic: image.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: minsung078940@gmail.com # Add your Email address
phone: 010 3128 5486 # Add your Phone number
website: rlaalastjd.github.io # Add your website, do not add http://\
github: rlaalastjd # Add your Github handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
